language: node_js
sudo: required
node_js:
  - '5'

before_install:
  - "source /etc/lsb-release"
  - "echo \"deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main\" | sudo tee /etc/apt/sources.list.d/rethinkdb.list"
  - "wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -"
  - "sudo apt-get update -y"

install:
  - "sudo apt-get install rethinkdb -y"
  - "npm install -g mocha gulp"
  - "npm install"
  - "rethinkdb&"

script:
  - "npm run test"
