language: node_js
sudo: false

services:
  - docker

node_js:
  - 7

addons:
  rethinkdb: 2.3

install:
  - npm install -g mocha gulp
  - npm install

script:
  - npm run test:coverage
  - npm run lint

after_script:
  - npm run coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t buckless/server .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push buckless/server;
    fi
